### ISSUE TITLE
cider-nrepl dep version

### ISSUE THREAD

**Issue by ccann** [camsaul/lein-check-namespace-decls#5]
@camsaul 
I just upgraded to cider 0.21.0 which depends on cider-nrepl 0.21.1. Having this plugin specified breaks CIDER because of the dependency version conflict.
Does `lein-check-namespace-decls` need a hard dependency on `cider-nrepl` or can it be a dev dependency?
I was able to work around with 
`:plugins              [[lein-check-namespace-decls "1.0.1" :exclusions [cider/cider-nrepl]]]`

**Comment by camsaul** [comment]
Hey @ccann, it is actually used, it's a "provided" dependency of `refactor-nrepl`. I went ahead and updated it to the latest version which should fix your issues (PR #7/release 1.0.2)

Using `:exclusions` is a good idea or what I like to do is make the command an alias that adds a profile that includes the plugin dependency. That way the dependency is isolated from everything else:

```clj
(defproject my-project "1.0.0"
  :aliases
  {"check-namespace-decls" ["with-profile" "+check-namespace-decls" "check-namespace-decls"]}

  :profiles
  :check-namespace-decls
  {:plugins
   [[lein-check-namespace-decls "1.0.2"]]}
```
